# Non-Mod-Specific Properties
modLoader = "javafml"
loaderVersion = "[42,)"
license = "GNU General Public License v3.0"
issueTrackerURL="https://github.com/ShadowGry/emerald-tools/issues"

# Mod Properties
[[mods]]
	modId = "emeraldtools"
	version = "${file.jarVersion}"
	displayName = "Emerald Tools"
	updateJSONURL = "https://raw.githubusercontent.com/ShadowGry/emerald-tools/HEAD/update.json"
	displayURL = "https://github.com/ShadowGry/emerald-tools"
	# logoFile = ""
	credits = "TechnoVision"
	authors = "ShadowGry"
	description = "Adds emerald tools and armor."

# Dependency Configurations
[[dependencies.coppertools]]
	modId = "forge"
	mandatory = true
	versionRange = "[42,)"
	ordering = "NONE"
	side = "BOTH"

[[dependencies.coppertools]]
	modId = "minecraft"
	mandatory = true
	versionRange = "[1.19.1,1.20)"
	ordering = "NONE"
	side = "BOTH"
